"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var EOrderAction;
(function (EOrderAction) {
    EOrderAction[EOrderAction["ORDER_ACTION_BUY"] = 0] = "ORDER_ACTION_BUY";
    EOrderAction[EOrderAction["ORDER_ACTION_SELL"] = 1] = "ORDER_ACTION_SELL";
    EOrderAction[EOrderAction["ORDER_ACTION_CREATE"] = 2] = "ORDER_ACTION_CREATE";
    EOrderAction[EOrderAction["ORDER_ACTION_REDEMPTION"] = 3] = "ORDER_ACTION_REDEMPTION";
    EOrderAction[EOrderAction["ORDER_ACTION_REPO"] = 4] = "ORDER_ACTION_REPO";
    EOrderAction[EOrderAction["ORDER_ACTION_REVERSE_REPO"] = 5] = "ORDER_ACTION_REVERSE_REPO";
    EOrderAction[EOrderAction["ORDER_ACTION_EXECUTION"] = 6] = "ORDER_ACTION_EXECUTION";
    EOrderAction[EOrderAction["ORDER_ACTION_LOCK"] = 7] = "ORDER_ACTION_LOCK";
    EOrderAction[EOrderAction["ORDER_ACTION_UNLOCK"] = 8] = "ORDER_ACTION_UNLOCK";
    EOrderAction[EOrderAction["ORDER_ACTION_TRANSFER_AGREEMENT"] = 9] = "ORDER_ACTION_TRANSFER_AGREEMENT";
    EOrderAction[EOrderAction["ORDER_ACTION_MARKET_MAKING_TRANSFER"] = 10] = "ORDER_ACTION_MARKET_MAKING_TRANSFER";
    EOrderAction[EOrderAction["ORDER_ACTION_SUBSCRIPTION"] = 11] = "ORDER_ACTION_SUBSCRIPTION";
    EOrderAction[EOrderAction["ORDER_ACTION_NONE"] = 255] = "ORDER_ACTION_NONE";
})(EOrderAction = exports.EOrderAction || (exports.EOrderAction = {}));
;
var EOrderProperty;
(function (EOrderProperty) {
    EOrderProperty[EOrderProperty["ORDER_PROPERTY_UNKNOW"] = 0] = "ORDER_PROPERTY_UNKNOW";
    EOrderProperty[EOrderProperty["ORDER_PROPERTY_XJ"] = 1] = "ORDER_PROPERTY_XJ";
    EOrderProperty[EOrderProperty["ORDER_PROPERTY_SJ"] = 2] = "ORDER_PROPERTY_SJ";
    EOrderProperty[EOrderProperty["ORDER_PROPERTY_AGREEMENT"] = 3] = "ORDER_PROPERTY_AGREEMENT";
    EOrderProperty[EOrderProperty["ORDER_PROPERTY_AGREEMENT_BOTH"] = 4] = "ORDER_PROPERTY_AGREEMENT_BOTH";
    EOrderProperty[EOrderProperty["ORDER_PROPERTY_DEFINED"] = 5] = "ORDER_PROPERTY_DEFINED";
})(EOrderProperty = exports.EOrderProperty || (exports.EOrderProperty = {}));
;
var EOrderCoveredFlag;
(function (EOrderCoveredFlag) {
    EOrderCoveredFlag[EOrderCoveredFlag["ORDER_COVERED_FLAG_NULL"] = 0] = "ORDER_COVERED_FLAG_NULL";
    EOrderCoveredFlag[EOrderCoveredFlag["ORDER_COVERED_FLAG_UNCOVER"] = 1] = "ORDER_COVERED_FLAG_UNCOVER";
    EOrderCoveredFlag[EOrderCoveredFlag["ORDER_COVERED_FLAG_COVER"] = 2] = "ORDER_COVERED_FLAG_COVER";
})(EOrderCoveredFlag = exports.EOrderCoveredFlag || (exports.EOrderCoveredFlag = {}));
;
var EOrderCurrency;
(function (EOrderCurrency) {
    EOrderCurrency[EOrderCurrency["ORDER_CURRENCY_UNKNOW"] = 0] = "ORDER_CURRENCY_UNKNOW";
    EOrderCurrency[EOrderCurrency["ORDER_CURRENCY_RMB"] = 1] = "ORDER_CURRENCY_RMB";
    EOrderCurrency[EOrderCurrency["ORDER_CURRENCY_HK"] = 2] = "ORDER_CURRENCY_HK";
    EOrderCurrency[EOrderCurrency["ORDER_CURRENCY_DOLLAR"] = 3] = "ORDER_CURRENCY_DOLLAR";
})(EOrderCurrency = exports.EOrderCurrency || (exports.EOrderCurrency = {}));
;
var EOrderStatus;
(function (EOrderStatus) {
    EOrderStatus[EOrderStatus["ORDER_STATUS_INVALID"] = 0] = "ORDER_STATUS_INVALID";
    EOrderStatus[EOrderStatus["ORDER_STATUS_INIT"] = 1] = "ORDER_STATUS_INIT";
    EOrderStatus[EOrderStatus["ORDER_STATUS_WAIT_SEND"] = 2] = "ORDER_STATUS_WAIT_SEND";
    EOrderStatus[EOrderStatus["ORDER_STATUS_SEND"] = 3] = "ORDER_STATUS_SEND";
    EOrderStatus[EOrderStatus["ORDER_STATUS_SEND_WAIT_CANCEL"] = 4] = "ORDER_STATUS_SEND_WAIT_CANCEL";
    EOrderStatus[EOrderStatus["ORDER_STATUS_PART_WAIT_CANCEL"] = 5] = "ORDER_STATUS_PART_WAIT_CANCEL";
    EOrderStatus[EOrderStatus["ORDER_STATUS_PART_CANCELED"] = 6] = "ORDER_STATUS_PART_CANCELED";
    EOrderStatus[EOrderStatus["ORDER_STATUS_CANCELED"] = 7] = "ORDER_STATUS_CANCELED";
    EOrderStatus[EOrderStatus["ORDER_STATUS_PART_DEALED"] = 8] = "ORDER_STATUS_PART_DEALED";
    EOrderStatus[EOrderStatus["ORDER_STATUS_DEALED"] = 9] = "ORDER_STATUS_DEALED";
    EOrderStatus[EOrderStatus["ORDER_STATUS_DISCARDED"] = 10] = "ORDER_STATUS_DISCARDED"; //10:废单            end status
})(EOrderStatus = exports.EOrderStatus || (exports.EOrderStatus = {}));
;
var EOrderStatusGW;
(function (EOrderStatusGW) {
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_SEND_PICK"] = 0] = "ORDER_STATUS_GW_SEND_PICK";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_SEND_CONFIRM"] = 1] = "ORDER_STATUS_GW_SEND_CONFIRM";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_CANCEL"] = 2] = "ORDER_STATUS_GW_CANCEL";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_INNER_CANCEL"] = 3] = "ORDER_STATUS_GW_INNER_CANCEL";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_ALL_DEALED"] = 4] = "ORDER_STATUS_GW_ALL_DEALED";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_PART_DEALED"] = 5] = "ORDER_STATUS_GW_PART_DEALED";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_CANCEL_DEALED"] = 6] = "ORDER_STATUS_GW_CANCEL_DEALED";
    EOrderStatusGW[EOrderStatusGW["ORDER_STATUS_GW_MATCH_DENLED"] = 7] = "ORDER_STATUS_GW_MATCH_DENLED"; //撮合被拒
})(EOrderStatusGW = exports.EOrderStatusGW || (exports.EOrderStatusGW = {}));
;
var EOrderType;
(function (EOrderType) {
    EOrderType[EOrderType["ORDER_TYPE_ORDER"] = 0] = "ORDER_TYPE_ORDER";
    EOrderType[EOrderType["ORDER_TYPE_CANCEL"] = 1] = "ORDER_TYPE_CANCEL";
    EOrderType[EOrderType["ORDER_TYPE_UNKNOWN"] = 255] = "ORDER_TYPE_UNKNOWN";
})(EOrderType = exports.EOrderType || (exports.EOrderType = {}));
;
var EStrategyStatus;
(function (EStrategyStatus) {
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_INIT"] = 0] = "STRATEGY_STATUS_INIT";
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_CREATE"] = 1] = "STRATEGY_STATUS_CREATE";
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_RUN"] = 2] = "STRATEGY_STATUS_RUN";
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_PAUSE"] = 3] = "STRATEGY_STATUS_PAUSE";
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_STOP"] = 4] = "STRATEGY_STATUS_STOP";
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_WATCH"] = 5] = "STRATEGY_STATUS_WATCH";
    EStrategyStatus[EStrategyStatus["STRATEGY_STATUS_ERROR"] = 6] = "STRATEGY_STATUS_ERROR";
})(EStrategyStatus = exports.EStrategyStatus || (exports.EStrategyStatus = {}));
;
var ESSSecuMarket;
(function (ESSSecuMarket) {
    ESSSecuMarket[ESSSecuMarket["SS_SECU_MARKET_UNKNOW"] = 0] = "SS_SECU_MARKET_UNKNOW";
    ESSSecuMarket[ESSSecuMarket["SS_SECU_MARKET_EQUIT"] = 1] = "SS_SECU_MARKET_EQUIT";
    ESSSecuMarket[ESSSecuMarket["SS_SECU_MARKET_FUTURE"] = 2] = "SS_SECU_MARKET_FUTURE";
})(ESSSecuMarket = exports.ESSSecuMarket || (exports.ESSSecuMarket = {}));
;
var ESSSecuCategory;
(function (ESSSecuCategory) {
    ESSSecuCategory[ESSSecuCategory["SS_SECU_CATEGORY_UNKNOW"] = 0] = "SS_SECU_CATEGORY_UNKNOW";
    ESSSecuCategory[ESSSecuCategory["SS_SECU_CATEGORY_EQUIT"] = 1] = "SS_SECU_CATEGORY_EQUIT";
    ESSSecuCategory[ESSSecuCategory["SS_SECU_CATEGORY_FUTURE"] = 2] = "SS_SECU_CATEGORY_FUTURE";
})(ESSSecuCategory = exports.ESSSecuCategory || (exports.ESSSecuCategory = {}));
;
var EOrderAlgorid;
(function (EOrderAlgorid) {
    EOrderAlgorid[EOrderAlgorid["ORDER_ALGORID_ALL"] = 0] = "ORDER_ALGORID_ALL";
    EOrderAlgorid[EOrderAlgorid["ORDER_ALGORID_REST"] = 5000] = "ORDER_ALGORID_REST";
    EOrderAlgorid[EOrderAlgorid["ORDER_ALGORID_HEDGE"] = 5001] = "ORDER_ALGORID_HEDGE";
})(EOrderAlgorid = exports.EOrderAlgorid || (exports.EOrderAlgorid = {}));
;
var EOrderAlgorIndex;
(function (EOrderAlgorIndex) {
    EOrderAlgorIndex[EOrderAlgorIndex["ORDER_ALGORINDEX_ALL"] = 0] = "ORDER_ALGORINDEX_ALL";
})(EOrderAlgorIndex = exports.EOrderAlgorIndex || (exports.EOrderAlgorIndex = {}));
;
var EOrderPriceType;
(function (EOrderPriceType) {
    EOrderPriceType[EOrderPriceType["ORDER_STATUS_TYPE_UNKNOWN"] = 0] = "ORDER_STATUS_TYPE_UNKNOWN";
    EOrderPriceType[EOrderPriceType["ORDER_STATUS_TYPE_ACTIVE"] = 1] = "ORDER_STATUS_TYPE_ACTIVE";
    EOrderPriceType[EOrderPriceType["ORDER_STATUS_TYPE_PASSIVE"] = 2] = "ORDER_STATUS_TYPE_PASSIVE";
})(EOrderPriceType = exports.EOrderPriceType || (exports.EOrderPriceType = {}));
;
var EOrderTradeType;
(function (EOrderTradeType) {
    EOrderTradeType[EOrderTradeType["ORDER_TRADE_TYPE_UNKNOWN"] = 0] = "ORDER_TRADE_TYPE_UNKNOWN";
    EOrderTradeType[EOrderTradeType["ORDER_TRADE_TYPE_OPEN"] = 1] = "ORDER_TRADE_TYPE_OPEN";
    EOrderTradeType[EOrderTradeType["ORDER_TRADE_TYPE_CLOSE"] = 2] = "ORDER_TRADE_TYPE_CLOSE";
    EOrderTradeType[EOrderTradeType["ORDER_TRADE_TYPE_CLOSE_TODAY"] = 3] = "ORDER_TRADE_TYPE_CLOSE_TODAY";
    EOrderTradeType[EOrderTradeType["ORDER_TRADE_TYPE_CLOSE_YESTERDAY"] = 4] = "ORDER_TRADE_TYPE_CLOSE_YESTERDAY";
})(EOrderTradeType = exports.EOrderTradeType || (exports.EOrderTradeType = {}));
;
var StrategyCfgType;
(function (StrategyCfgType) {
    StrategyCfgType[StrategyCfgType["STRATEGY_CFG_TYPE_INSTRUMENT"] = 0] = "STRATEGY_CFG_TYPE_INSTRUMENT";
    StrategyCfgType[StrategyCfgType["STRATEGY_CFG_TYPE_COMMENT"] = 1] = "STRATEGY_CFG_TYPE_COMMENT";
    StrategyCfgType[StrategyCfgType["STRATEGY_CFG_TYPE_PARAMETER"] = 2] = "STRATEGY_CFG_TYPE_PARAMETER";
    StrategyCfgType[StrategyCfgType["STRATEGY_CFG_TYPE_COMMAND"] = 3] = "STRATEGY_CFG_TYPE_COMMAND";
})(StrategyCfgType = exports.StrategyCfgType || (exports.StrategyCfgType = {}));
;
var EObjectInfoType;
(function (EObjectInfoType) {
    EObjectInfoType[EObjectInfoType["STRATEGY_CFG_TYPE_NONE"] = 0] = "STRATEGY_CFG_TYPE_NONE";
    EObjectInfoType[EObjectInfoType["OBJECT_INFO_TYPE_VALUE"] = 1] = "OBJECT_INFO_TYPE_VALUE";
    EObjectInfoType[EObjectInfoType["STRATEGY_CFG_TYPE_OBJECT"] = 2] = "STRATEGY_CFG_TYPE_OBJECT";
})(EObjectInfoType = exports.EObjectInfoType || (exports.EObjectInfoType = {}));
;
var EValueType;
(function (EValueType) {
    EValueType[EValueType["VALUE_TYPE_NONE"] = 0] = "VALUE_TYPE_NONE";
    EValueType[EValueType["VALUE_TYPE_CHAR"] = 1] = "VALUE_TYPE_CHAR";
    EValueType[EValueType["VALUE_TYPE_CHARPTR"] = 2] = "VALUE_TYPE_CHARPTR";
    EValueType[EValueType["VALUE_TYPE_BYTE"] = 3] = "VALUE_TYPE_BYTE";
    EValueType[EValueType["VALUE_TYPE_BYTEPTR"] = 4] = "VALUE_TYPE_BYTEPTR";
    EValueType[EValueType["VALUE_TYPE_SHORT"] = 5] = "VALUE_TYPE_SHORT";
    EValueType[EValueType["VALUE_TYPE_SHORTPTR"] = 6] = "VALUE_TYPE_SHORTPTR";
    EValueType[EValueType["VALUE_TYPE_USHORT"] = 7] = "VALUE_TYPE_USHORT";
    EValueType[EValueType["VALUE_TYPE_USHORTPTR"] = 8] = "VALUE_TYPE_USHORTPTR";
    EValueType[EValueType["VALUE_TYPE_INT"] = 9] = "VALUE_TYPE_INT";
    EValueType[EValueType["VALUE_TYPE_INTPTR"] = 10] = "VALUE_TYPE_INTPTR";
    EValueType[EValueType["VALUE_TYPE_UINT"] = 11] = "VALUE_TYPE_UINT";
    EValueType[EValueType["VALUE_TYPE_UINTPTR"] = 12] = "VALUE_TYPE_UINTPTR";
    EValueType[EValueType["VALUE_TYPE_LONG"] = 13] = "VALUE_TYPE_LONG";
    EValueType[EValueType["VALUE_TYPE_LONGPTR"] = 14] = "VALUE_TYPE_LONGPTR";
    EValueType[EValueType["VALUE_TYPE_ULONG"] = 15] = "VALUE_TYPE_ULONG";
    EValueType[EValueType["VALUE_TYPE_ULONGPTR"] = 16] = "VALUE_TYPE_ULONGPTR";
    EValueType[EValueType["VALUE_TYPE_INT64"] = 17] = "VALUE_TYPE_INT64";
    EValueType[EValueType["VALUE_TYPE_INT64PTR"] = 18] = "VALUE_TYPE_INT64PTR";
    EValueType[EValueType["VALUE_TYPE_UINT64"] = 19] = "VALUE_TYPE_UINT64";
    EValueType[EValueType["VALUE_TYPE_UINT64PTR"] = 20] = "VALUE_TYPE_UINT64PTR";
    EValueType[EValueType["VALUE_TYPE_FLOAT"] = 21] = "VALUE_TYPE_FLOAT";
    EValueType[EValueType["VALUE_TYPE_FLOATPTR"] = 22] = "VALUE_TYPE_FLOATPTR";
    EValueType[EValueType["VALUE_TYPE_DOUBLE"] = 23] = "VALUE_TYPE_DOUBLE";
    EValueType[EValueType["VALUE_TYPE_DOUBLEPTR"] = 24] = "VALUE_TYPE_DOUBLEPTR";
    EValueType[EValueType["VALUE_TYPE_STRING"] = 25] = "VALUE_TYPE_STRING";
    EValueType[EValueType["VALUE_TYPE_STRINGPTR"] = 26] = "VALUE_TYPE_STRINGPTR";
})(EValueType = exports.EValueType || (exports.EValueType = {}));
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
//# sourceMappingURL=orderstruct.js.map